/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edaf60.xl.group;

import edaf60.xl.gui.XL;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        
        XL.main(args);


    }
}
